#---Notifcations---

notifications:
  email: false

#---Language---

language: python

cache: pip

#---Branches---

branches:
  only:
    - master
    - travis_config

#---Environment---

matrix:
  include:
    - python: "2.6"
      env: ANSIBLE_VERSION="2.5.3"  # Version in RHEL6 EPEL repo
    - python: "2.7"
      env: ANSIBLE_VERSION="2.5.4"  # Latest version
    - python: "2.7"
      env: ANSIBLE_VERSION="2.4.2"  # Version in RHEL7 repo
    - python: "2.7"
      env: ANSIBLE_VERSION="2.3.3"  # Last 2.3.x version  
    - python: "3.5"
      env: ANSIBLE_VERSION="2.5.4"  # Latest version 
    - python: "3.6"
      env: ANSIBLE_VERSION="2.5.4"  # Latest version

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - firefox
      - google-chrome-stable

#---Services---

#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:
  - pip install -q ansible==$ANSIBLE_VERSION
  - pip install selenium

 #--Before Script--

 #--Script--

# Many warnings are ignored on the Idempotence run, this is to reduce clutter, making it easier to see which tasks are not idempotent, all default warnings are enabled for the first run

script:
# First run Test
  - "echo 'allow_world_readable_tmpfiles=True' >> ansible.cfg"		# Allows world readable temp files, not secure should only be used within Travis
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --extra-vars '@presets/travis_4.9.1.yml'"
#
# Deletion Script Test
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --extra-vars '@presets/travis_4.9.1.yml' --extra-vars 'delete_fac=true'  --tags 'pycat'"
#
# Idempotence Test
#  - "sed -i 's/delete_fac: true/delete_fac: false/g' config.yml"	# Test Idempotence
#  - "echo 'stdout_callback = actionable' >> ansible.cfg"		# Only Output Changed or Failed Tasks
#  - "echo 'deprecation_warnings = False' >> ansible.cfg"		# Ignore Depriciation Warnings
#  - "echo 'command_warnings = False' >> ansible.cfg"			# Ignore Command Module Warnings
#  - "echo 'system_warnings = False' >> ansible.cfg"			# Ignore System Warnings
#  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --extra-vars '@presets/travis_4.9.1.yml' --diff"  
# Reduce changed tasks to lowest possible number (0 if possible) then check that changed value does not exceed that, fail if it does 
#
# Interface Test
  - "cd $(cat presets/travis_4.9.1.yml | grep travis_path | sed 's/travis_path: //g')"
  - "cat test_args | sudo xargs xvfb-run python topcat_selenium_test.py"
#
# Experiemental Interface test (Uncomment once getting args from ansible is figured out)
#  - "mkdir Topcat_Selnium_Tests"
#  - "cd Topcat_Selnium_Tests"
#  - "cat test_args | sudo xargs xvfb-run python topcat_selenium_test.py"

 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
